require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"

-- Colorscheme
spec "user.colorscheme"

-- Essenital plugins
spec "user.alpha"
spec "user.autopairs"
spec "user.breadcrumbs"
spec "user.cmp"
spec "user.comment"
spec "user.devicons"
spec "user.gitsigns"
spec "user.harpoon"
spec "user.illuminate"
spec "user.indentline"
spec "user.lspconfig"
spec "user.lualine"
spec "user.mason"
spec "user.navic"
spec "user.navigator"
spec "user.lazygit"
spec "user.neotest"
spec "user.none-ls"
spec "user.nvimtree"
spec "user.project"
spec "user.schemastore"
spec "user.telescope"
spec "user.toggleterm"
spec "user.treesitter"
spec "user.whichkey"

-- Extra plugins
spec "user.extras.oil"
spec "user.extras.eyeliner"
spec "user.extras.cellular-automaton"
spec "user.extras.copilot"
spec "user.extras.navbuddy"

require "user.lazy"
